spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
            - classpath:/configs/{application}
            - classpath:/configs/{application}/{profile}
      fail-fast: true
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:config}
      password: ${CONFIG_SERVER_PASSWORD:config}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
server:
  port: 8081