spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
            search-locations:
              - /configs
              - /configs/{application}
              - /configs/{application}/{profile}
              - classpath:/configs
              - classpath:/configs/{application}
              - classpath:/configs/{application}/{profile}
      fail-fast: true
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:config}
      password: ${CONFIG_SERVER_PASSWORD:config}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/, http://localhost:8761/eureka/
    register-with-eureka: true
