spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
            search-locations:
              - file:///configs
              - file:///configs/{application}
              - file:///configs/{application}/{profile}
              - classpath:/configs
              - classpath:/configs/{application}
              - classpath:/configs/{application}/{profile}
      fail-fast: true
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:config}
      password: ${CONFIG_SERVER_PASSWORD:config}

